package incident.platform.service.ai;

import incident.platform.service.config.OpenRouterProperties;
import incident.platform.service.entity.IncidentAnalysisEntity;
import incident.platform.service.entity.IncidentLogEntity;
import incident.platform.service.repository.IncidentAnalysisRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

@Service
@RequiredArgsConstructor
@Slf4j
public class AIAnalysisService {

    private final OpenRouterProperties properties;
    private final IncidentAnalysisRepository analysisRepository;

    public void analyzeIncident(
            IncidentLogEntity incidentLogEntity) {

        String prompt = buildPrompt(incidentLogEntity);

        WebClient webClient =
                WebClient.builder()
                        .baseUrl(properties.getUrl())
                        .defaultHeader(
                                HttpHeaders.AUTHORIZATION,
                                "Bearer " + properties.getKey()
                        )
                        .defaultHeader(
                                HttpHeaders.CONTENT_TYPE,
                                MediaType.APPLICATION_JSON_VALUE
                        )
                        .build();

        String requestBody = """
        {
          "model":"%s",
          "messages":[
            {
              "role":"user",
              "content":"%s"
            }
          ]
        }
        """.formatted(
                properties.getModel(),
                prompt.replace("\"", "\\\"")
        );

        String response =
                webClient.post()
                        .bodyValue(requestBody)
                        .retrieve()
                        .bodyToMono(String.class)
                        .block();

        IncidentAnalysisEntity analysis =
                IncidentAnalysisEntity.builder()
                        .incidentId(
                                incidentLogEntity.getId()
                        )
                        .severity("PENDING_PARSE")
                        .rootCause("Generated By AI")
                        .recommendation("Generated By AI")
                        .aiSummary(response)
                        .modelName(properties.getModel())
                        .analysisStatus("SUCCESS")
                        .build();

        analysisRepository.save(analysis);
    }

    private String buildPrompt(
            IncidentLogEntity incident) {

        return """
                Analyze the following production incident.

                Service Name:
                %s

                Environment:
                %s

                Log Level:
                %s

                Exception:
                %s

                Log Message:
                %s

                Stack Trace:
                %s

                Provide:
                1. Severity
                2. Root Cause
                3. Recommendation
                4. Summary
                """
                .formatted(
                        incident.getServiceName(),
                        incident.getEnvironment(),
                        incident.getLogLevel(),
                        incident.getExceptionName(),
                        incident.getLogMessage(),
                        incident.getStackTrace()
                );
    }
}
